title: santa-detector-scratch2
hero_image: images/banner.png
description: santa-detector-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-20"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
